var www_chatbots = [
    {
        name: "Gemini",
        url: "https://gemini.google.com/app",
        provider: "Google",
        features: [],
    },
    { name: "Grok", url: "https://grok.com/", provider: "xAI", features: [] },
    { name: "Claude", url: "", provider: "Anthropic", features: [] },
    {
        name: "ChatGPT",
        url: "https://chatgpt.com/",
        provider: "OpenAI",
        features: [],
    },
    {
        name: "Allen AI",
        url: "https://playground.allenai.org/",
        provider: "Allen Institute for AI",
        features: [],
    },
    {
        name: "Le Chat",
        url: "https://chat.mistral.ai/chat",
        provider: "Mistral AI",
        features: [],
    },
    {
        name: "Meta AI",
        url: "https://www.meta.ai/",
        provider: "Meta",
        features: [],
    },
    {
        name: "Qwen",
        url: "https://chat.qwen.ai/",
        provider: "Alibaba",
        features: [],
    },
    {
        name: "Deepseek AI",
        url: "https://chat.deepseek.com/",
        provider: "DeepSeek",
        features: [],
    },
    {
        name: "Kimi",
        url: "https://www.kimi.com/",
        provider: "Moonshot AI",
        features: [],
    },
    {
        name: "Manus AI",
        url: "https://manus.im/app",
        provider: "Manus",
        features: [],
    },
    { name: "Z.ai", url: "https://z.ai/chat", provider: "Z.ai", features: [] },
    {
        name: "Perplexity AI",
        url: "https://www.perplexity.ai/",
        provider: "Perplexity AI",
        features: [],
    },
    {
        name: "Deep Cogito",
        url: "https://chat.deepcogito.com/",
        provider: "Deep Cogito",
        features: [],
    },
    {
        name: "HuggingChat",
        url: "https://huggingface.co/chat/",
        provider: "Hugging Face",
        features: [],
    },
];
